# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a173f149d531478d7f0a006335bed5b0ed2bebdf3dec9bfeef786e6e3995d60587e114aa8ac17cbe9f151b69bac94ca6f750eee11375a9263f76dabae55ae64f

test:
  secret_key_base: bc51cefba0abd393d77dbaace20687296b103fbeb4f63d1a86308038715a1bef59ef741085167b624a88151e183178c7e8d675aabe638f51a608fed43149c6c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
